name: Annotations with FORCE_COLOR false do show up

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx nx run app:lint
        env:
          FORCE_COLOR: false
